namespace: "manta-ray-plan-production"

image:
  tag: "v0.4.6"

clusterIssuer:
  enabled: true

domain:
  default: "www.mad-world.nl"

admin:
  bff:
    host: "admin-bff-mantarayplan.mad-world.nl"
  web:
    host: "admin-mantarayplan.mad-world.nl"

viewer:
  bff:
    host: "viewer-bff-mantarayplan.mad-world.nl"
  web:
    host: "mantarayplan.mad-world.nl"

logging:
  seq:
    outsideAccess: 
      enable: true
    host:
      external: "seq.mad-world.nl"
    firstTimePassword: "QFCKH3NTSBQ5zmsH9DpXTB2YefIavEGJKa4SshKb11AXX8b4o4KPjuo9bd6WBfqDkpxKqzNjaOrCsE49ph369Wx84mIrksnJx5OtRcxAOjff"

database:
  size:
    single: 10Gi
    combined: 35Gi

pgadmin:
  outsideAccess: 
    enabled: true
  host: "database.mad-world.nl"