apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.grpc.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.grpc.app }}
    name: {{ .Values.api.grpc.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.grpc.app }}
      task: {{ .Values.api.grpc.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.grpc.app }}
        task: {{ .Values.api.grpc.name }}
    spec:
      serviceAccountName: {{ .Values.serveraccount.name }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.api.grpc.app }}
          image: "{{ .Values.api.grpc.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              ephemeral-storage: "1Gi"
              cpu: 0.5
              memory: "500Mi"
            limits:
              ephemeral-storage: "2Gi"
              cpu: 1
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3 
          env:
            - name: Database__Host
              value: "postgres-ro"
            - name: Database__Port
              value: "5432"
            - name: Database__DbName
              value: {{ .Values.database.dbName }}
            - name: Database__User
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: username
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: password      
            - name: OpenTelemetry__LoggerEndpoint
              value: "{{ .Values.logging.seq.host.internal }}"
            - name: OpenTelemetry__LoggerApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.logging.seq.secrets.name }}
                  key: apiKeyGrpc
            - name: Kestrel__EndpointDefaults__Protocols
              value: "Http1AndHttp2"
            - name: MessageBus__Host
              value: {{ .Values.messageBus.loadBalancer }}
            - name: MessageBus__Username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageBus.secret.name }}
                  key: username
            - name: MessageBus__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageBus.secret.name }}
                  key: password        
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.grpc.loadBalancer }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.api.grpc.app }}
    task: {{ .Values.api.grpc.name }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer