{{- $postgresSecrets := (lookup "v1" "Secret" .Values.namespace .Values.database.name ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ "app" | b64enc }}
{{- if and $postgresSecrets $postgresSecrets.data }}
  {{- if $postgresSecrets.data.password }}
  password: {{ $postgresSecrets.data.password }}
  {{- else }}
  password: {{ "nonExistingKey1234" | b64enc }}
  {{- end }}
{{- else }}
  password: {{ "nonExistingKey1234" | b64enc }}
{{- end }}
---
{{- if .Values.database.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Values.namespace }}
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: {{ .Values.database.dbName }}
      owner: app
      secret: 
        name: postgres-secret
  storage:
    size: {{ .Values.database.size.single }}
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.database.size.single }}
      storageClassName: {{ .Values.database.storageclass }}
{{ end }}