apiVersion: v1
data:
  username: YXBw
  password: U2VjcmV0MTIzNA==
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
---
apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
  namespace: hostpath-provisioner
spec:
  imagePullPolicy: Always
  storagePools:
    - name: "postgres-pool"
      pvcTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.database.size.combined }}
      path: "/MantaRayPlan/Postgres"
  workload:
    nodeSelector:
      kubernetes.io/os: linux
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-csi
  namespace: hostpath-provisioner
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePool: postgres-pool
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: maintenance
      owner: app
      secret: 
        name: postgres-secret
  storage:
    size: {{ .Values.database.size.single }}
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.database.size.single }}
      storageClassName: postgres-csi
  
