apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.viewer.web.app }}-nginx-config"
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        add_header X-Frame-Options "SAMEORIGIN" always;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.viewer.web.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.viewer.web.app }}
    name: {{ .Values.viewer.web.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.viewer.web.app }}
      task: {{ .Values.viewer.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.viewer.web.app }}
        task: {{ .Values.viewer.web.name }}
    spec:
      containers:
        - name: {{ .Values.viewer.web.app }}
          image: "{{ .Values.viewer.web.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz.txt
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          volumeMounts:
            - name: "{{ .Values.viewer.web.app }}-nginx-config-volume"
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          ports:
            - containerPort: 80
      volumes:
        - name: "{{ .Values.viewer.web.app }}-nginx-config-volume"
          configMap:
            name: "{{ .Values.viewer.web.app }}-nginx-config"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.viewer.web.loadBalancer }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.viewer.web.app }}
    task: {{ .Values.viewer.web.name }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer