apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.viewer.bff.deployment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.viewer.bff.app }}
    name: {{ .Values.viewer.bff.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.viewer.bff.app }}
      task: {{ .Values.viewer.bff.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.viewer.bff.app }}
        task: {{ .Values.viewer.bff.name }}
    spec:
      containers:
        - name: {{ .Values.viewer.bff.app }}
          image: "{{ .Values.viewer.bff.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              ephemeral-storage: "1Gi"
              memory: "500Mi"
            limits:
              ephemeral-storage: "2Gi"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: Api__Address
              value: "{{ .Values.api.grpc.loadBalancer }}:8080"
            - name: OpenTelemetry__LoggerEndpoint
              value: "{{ .Values.logging.seq.host.internal }}"
            - name: OpenTelemetry__LoggerApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.logging.seq.secrets.name }}
                  key: apiKeyViewer
            - name: MessageBus__Host
              value: {{ .Values.messageBus.loadBalancer }}
            - name: MessageBus__Username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageBus.secret.name }}
                  key: username
            - name: MessageBus__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.messageBus.secret.name }}
                  key: password  
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.viewer.bff.loadBalancer }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.viewer.bff.app }}
    task: {{ .Values.viewer.bff.name }}
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer