name: manta-ray-plan
services:
  api-web:
    image: ghcr.io/madworldnl/mantarayplan-api-web:latest
    container_name: api-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"