name: manta-ray-plan
services:
  admin-bff:
    image: ghcr.io/madworldnl/mantarayplan-admin-bff:latest
    container_name: admin-bff
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Admin.Bff/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  admin-web:
    image: ghcr.io/madworldnl/mantarayplan-admin-web:latest
    container_name: admin-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Admin.Web/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"
  api-grpc:
    image: ghcr.io/madworldnl/mantarayplan-api-grpc:latest
    container_name: api-grpc
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.Grpc/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8084:8080"
      - "8085:8081"
  api-message-bus:
    image: ghcr.io/madworldnl/mantarayplan-api-message-bus:latest
    container_name: api-message-bus
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.MessageBus/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8086:8080"
      - "8087:8081"
  viewer-bff:
    image: ghcr.io/madworldnl/mantarayplan-viewer-bff:latest
    container_name: viewer-bff
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Bff/Dockerfile
    ports:
      - "8088:8080"
      - "8089:8081"
  viewer-web:
    image: ghcr.io/madworldnl/mantarayplan-viewer-web:latest
    container_name: viewer-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Web/Dockerfile
    ports:
      - "8090:80"
      - "8091:443"
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      # The hashed password is in clear text: Secret1234
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QFCKH3NTSBQ5zmsH9DpXTB2YefIavEGJKa4SshKb11AXX8b4o4KPjuo9bd6WBfqDkpxKqzNjaOrCsE49ph369Wx84mIrksnJx5OtRcxAOjff
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret1234
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.nl
      - PGADMIN_DEFAULT_PASSWORD=Secret1234
    ports:
      - "9080:80"
      - "9081:443"
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-data:
  pgadmin-data:
  seq-data:
networks:
  postgres: