name: manta-ray-plan
services:
  admin-bff:
    image: ghcr.io/madworldnl/mantarayplan-admin-bff:latest
    container_name: admin-bff
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Admin.Bff/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  admin-web:
    image: ghcr.io/madworldnl/mantarayplan-admin-web:latest
    container_name: admin-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Admin.Web/Dockerfile
    ports:
      - "8082:80"
      - "8083:443"
  api-grpc:
    image: ghcr.io/madworldnl/mantarayplan-api-grpc:latest
    container_name: api-grpc
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.Grpc/Dockerfile
    ports:
      - "8084:8080"
      - "8085:8081"
  viewer-bff:
    image: ghcr.io/madworldnl/mantarayplan-viewer-bff:latest
    container_name: viewer-bff
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Bff/Dockerfile
    ports:
      - "8086:8080"
      - "8087:8081"
  viewer-web:
    image: ghcr.io/madworldnl/mantarayplan-viewer-web:latest
    container_name: viewer-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Web/Dockerfile
    ports:
      - "8088:80"
      - "8089:443"