name: manta-ray-plan
services:
  api-grpc:
    image: ghcr.io/madworldnl/mantarayplan-api-grpc:latest
    container_name: api-grpc
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.Grpc/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  viewer-bff:
    image: ghcr.io/madworldnl/mantarayplan-viewer-bff:latest
    container_name: viewer-bff
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Bff/Dockerfile
    ports:
      - "8082:8080"
      - "8083:8081"
  viewer-web:
    image: ghcr.io/madworldnl/mantarayplan-viewer-web:latest
    container_name: viewer-web
    profiles: [ all ]
    build:
      context: .
      dockerfile: Clients.Viewer.Web/Dockerfile
    ports:
      - "8084:80"
      - "8085:443"