name: manta-ray-plan
services:
  api-grpc:
    image: ghcr.io/madworldnl/mantarayplan-api-grpc:latest
    container_name: api-grpc
    profiles: [ all ]
    build:
      context: .
      dockerfile: Server.Controllers.Api.Grpc/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"